title: Deep Learning Portfolio
author: Joanna Reyda D. Santos
copyright: "2025"
logo: logo.png

execute:
  execute_notebooks: off

html:
  favicon: logo.png
  static_path:
    - _static
  css_files:
    - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
    - custom.css
  footer_items:
    - text: "Copyright Â© 2025, Joanna Reyda D. Santos"
  extra_footer: |
    <p>Powered by <a href="https://jupyterbook.org">Jupyter Book</a>.</p>
  mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  mathjax_config:
    tex:
      inlineMath: [["$", "$"], ["\\(", "\\)"]]
      displayMath: [["$$", "$$"], ["\\[", "\\]"]]
      tags: "ams"
      tagSide: "right"

repository:
  url: https://github.com/LadyJo02/deep-learning-portfolio
  branch: main
  path_to_book: mybook
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false

sphinx:
  config:
    html_theme_options:
      repository_url: "https://github.com/LadyJo02/deep-learning-portfolio"
      repository_branch: main
      path_to_docs: "mybook"
      use_repository_button: true
      use_issues_button: false
      use_edit_page_button: false

    html_static_path:
      - "_static"

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - colon_fence
    - deflist
